name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  stable:
    name: Push to stable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Readme/Assets Update
      uses: 10up/action-wordpress-plugin-asset-update@2.0.0
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: latepoint-manager